
server:
  port: 8086
spring:
  application:
    name: oauth2-service

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

vn:
  maven:
    security:
      cors:
        enable: true
